// Auto-generated by generateAirportTzList.ts
// Generated on: 2025-05-05T01:10:00.243Z
// Year-specific DST data for 2025

#include <stdint.h>

static const uint16_t airport_code_pool_bits[] = {
    0x3de6, /* PPG */
    0x2284, /* IUE */
    0x1668, /* FTI */
    0x1dab, /* HNL */
    0x29c0, /* KOA */
    0x2d07, /* LIH */
    0x226e, /* ITO */
    0x314a, /* MKK */
    0x24ec, /* JHM */
    0x2db8, /* LNY */
    0x6a, /* ADK */
    0x34f5, /* NHV */
    0x290, /* AUQ */
    0x500f, /* UAP */
    0x5007, /* UAH */
    0x1991, /* GMR */
    0x1a2, /* ANC */
    0x2c17, /* LAX */
    0x48ae, /* SFO */
    0x2c12, /* LAS */
    0x4880, /* SEA */
    0x62b1, /* YVR */
    0x480d, /* SAN */
    0x3c77, /* PDX */
    0x380a, /* OAK */
    0x4922, /* SJC */
    0x4985, /* SMF */
    0x49a0, /* SNA */
    0x4d09, /* TIJ */
    0x39b3, /* ONT */
    0x2cc1, /* LGB */
    0x691, /* BUR */
    0x3e4f, /* PSP */
    0x6309, /* YYJ */
    0x6176, /* YLW */
    0x1413, /* FAT */
    0x4820, /* SBA */
    0x3cf7, /* PHX */
    0xc8d, /* DEN */
    0x4962, /* SLC */
    0x6302, /* YYC */
    0x6086, /* YEG */
    0x30, /* ABQ */
    0x116f, /* ELP */
    0x3097, /* MEX */
    0x186b, /* GDL */
    0x3278, /* MTY */
    0x492e, /* SJO */
    0x3a23, /* ORD */
    0xcb6, /* DFW */
    0x2007, /* IAH */
    0x324f, /* MSP */
    0x3076, /* MDW */
    0xc0b, /* DAL */
    0x4a6b, /* STL */
    0x5a0, /* BNA */
    0x292, /* AUS */
    0x1dd4, /* HOU */
    0x3258, /* MSY */
    0x3048, /* MCI */
    0x4813, /* SAT */
    0x3980, /* OMA */
    0x62c6, /* YWG */
    0x3144, /* MKE */
    0x21e2, /* IPC */
    0x5c6, /* BOG */
    0xa8d, /* CUN */
    0x2d0c, /* LIM */
    0x1c15, /* HAV */
    0x26b, /* ATL */
    0x24aa, /* JFK */
    0x6319, /* YYZ */
    0x973, /* CLT */
    0x304e, /* MCO */
    0x3100, /* MIA */
    0x12d1, /* EWR */
    0x5d2, /* BOS */
    0xe76, /* DTW */
    0x156b, /* FLL */
    0x3a2b, /* ORL */
    0x2cc0, /* LGA */
    0x3ceb, /* PHL */
    0x6c8, /* BWI */
    0xc40, /* DCA */
    0x2003, /* IAD */
    0x4de0, /* TPA */
    0x328d, /* MUN */
    0x8c1, /* CGB */
    0x300e, /* MAO */
    0x4aec, /* SXM */
    0x8d1, /* CGR */
    0x3ea7, /* PVH */
    0x6a1, /* BVB */
    0x60f9, /* YHZ */
    0x484b, /* SCL */
    0x6313, /* YYT */
    0x6065, /* YDF */
    0x6018, /* YAY */
    0x6217, /* YQX */
    0x62cc, /* YWM */
    0x60b7, /* YFX */
    0x60e0, /* YHA */
    0x1a34, /* GRU */
    0x8c7, /* CGH */
    0x641, /* BSB */
    0x1906, /* GIG */
    0x8f, /* AEP */
    0x1324, /* EZE */
    0x9a5, /* CNF */
    0x544f, /* VCP */
    0x4874, /* SDU */
    0x3dc0, /* POA */
    0x4482, /* REC */
    0x4a40, /* SSA */
    0xac1, /* CWB */
    0x15d1, /* FOR */
    0x156d, /* FLN */
    0x48b, /* BEL */
    0x1b0d, /* GYN */
    0x5517, /* VIX */
    0x9d1, /* COR */
    0x3413, /* NAT */
    0x164f, /* FSP */
    0x148d, /* FEN */
    0x19c7, /* GOH */
    0x4903, /* SID */
    0x3c6b, /* PDL */
    0x4c91, /* TER */
    0x2885, /* KEF */
    0x2cf1, /* LHR */
    0x2cd6, /* LGW */
    0xe81, /* DUB */
    0x300d, /* MAN */
    0x2d12, /* LIS */
    0x4a6d, /* STN */
    0x2e6d, /* LTN */
    0x1068, /* EDI */
    0x2de0, /* LPA */
    0x4f7, /* BHX */
    0x4cb2, /* TFS */
    0x39ee, /* OPO */
    0x1960, /* GLA */
    0x140e, /* FAO */
    0x632, /* BRS */
    0x44, /* ACE */
    0x1684, /* FUE */
    0x4b2, /* BFS */
    0x344b, /* NCL */
    0x98d, /* CMN */
    0x866, /* CDG */
    0x192, /* AMS */
    0x1620, /* FRA */
    0x3003, /* MAD */
    0x44d, /* BCN */
    0x3282, /* MUC */
    0x144e, /* FCO */
    0x6627, /* ZRH */
    0x9e7, /* CPH */
    0x3d88, /* PMI */
    0x3a4b, /* OSL */
    0x22d, /* ARN */
    0x634, /* BRU */
    0xe92, /* DUS */
    0x5504, /* VIE */
    0x32ef, /* MXP */
    0x4eeb, /* TXL */
    0xcf, /* AGP */
    0x1c0c, /* HAM */
    0x1aa0, /* GVA */
    0x25a1, /* JNB */
    0x9f3, /* CPT */
    0xe91, /* DUR */
    0x2a33, /* KRT */
    0x28c3, /* KGD */
    0x4d75, /* TLV */
    0x498, /* BEY */
    0x2915, /* KIV */
    0x267, /* ATH */
    0x1c8b, /* HEL */
    0x3a6f, /* OTP */
    0x282f, /* KBP */
    0x1c91, /* HER */
    0x49c5, /* SOF */
    0x4946, /* SKG */
    0x4517, /* RIX */
    0x44ee, /* RHO */
    0x104d, /* ECN */
    0x1b20, /* GZA */
    0x808, /* CAI */
    0x1e26, /* HRG */
    0x4a47, /* SSH */
    0x1c24, /* HBE */
    0x2253, /* IST */
    0x4aae, /* SVO */
    0x2483, /* JED */
    0x4816, /* SAW */
    0xd84, /* DME */
    0x313, /* AYT */
    0x4687, /* RUH */
    0x554e, /* VKO */
    0x2c83, /* LED */
    0x1241, /* ESB */
    0x61, /* ADB */
    0x63, /* ADD */
    0x342e, /* NBO */
    0x3083, /* MED */
    0x91, /* AER */
    0x60, /* ADA */
    0x490f, /* SIP */
    0xd6c, /* DLM */
    0x3250, /* MSQ */
    0x535, /* BJV */
    0x4cf1, /* THR */
    0x30e3, /* MHD */
    0x2140, /* IKA */
    0x4b19, /* SYZ */
    0x2d9, /* AWZ */
    0x2907, /* KIH */
    0x20ad, /* IFN */
    0x4c39, /* TBZ */
    0x5a3, /* BND */
    0x3cd4, /* PGU */
    0x2891, /* KER */
    0x323, /* AZD */
    0x23, /* ABD */
    0x699, /* BUZ */
    0x6407, /* ZAH */
    0x3987, /* OMH */
    0x4412, /* RAS */
    0xee1, /* DXB */
    0x287, /* AUH */
    0x48e9, /* SHJ */
    0x3234, /* MRU */
    0x4c32, /* TBS */
    0x2a85, /* KUF */
    0x468d, /* RUN */
    0xec2, /* DWC */
    0x245, /* ASF */
    0x692, /* BUS */
    0x4553, /* RKT */
    0x2a93, /* KUT */
    0x212a, /* IJK */
    0x5178, /* ULY */
    0x282b, /* KBL */
    0x1c80, /* HEA */
    0x2867, /* KDH */
    0x3331, /* MZR */
    0x3199, /* MMZ */
    0x1423, /* FBD */
    0x4ab7, /* SVX */
    0x50a0, /* UFA */
    0x4d2c, /* TJM */
    0x48c2, /* SGC */
    0x88a, /* CEK */
    0x3c84, /* PEE */
    0x3697, /* NUX */
    0x448d, /* REN */
    0x3522, /* NJC */
    0x4978, /* SLY */
    0x1d80, /* HMA */
    0x35c9, /* NOJ */
    0x370c, /* NYM */
    0x3205, /* MQF */
    0x28cf, /* KGP */
    0xc8b, /* DEL */
    0x5cc, /* BOM */
    0x571, /* BLR */
    0x854, /* CCU */
    0x3000, /* MAA */
    0x9ca, /* COK */
    0x3db0, /* PNQ */
    0x183, /* AMD */
    0x19c8, /* GOI */
    0x2408, /* JAI */
    0x2d4e, /* LKO */
    0x1814, /* GAU */
    0x4e35, /* TRV */
    0x428, /* BBI */
    0x849, /* CCJ */
    0x3c13, /* PAT */
    0x2071, /* IDR */
    0x5679, /* VTZ */
    0x4af1, /* SXR */
    0x921, /* CJB */
    0x2a6c, /* KTM */
    0x6c0, /* BWA */
    0x511, /* BIR */
    0x288f, /* KEP */
    0x4de9, /* TPJ */
    0x4d88, /* TMI */
    0x4f1, /* BHR */
    0x46f, /* BDP */
    0x3992, /* OMS */
    0x44cd, /* RGN */
    0x306b, /* MDL */
    0x8ca, /* CGK */
    0x54a, /* BKK */
    0xd8a, /* DMK */
    0x48cd, /* SGN */
    0x1c0d, /* HAN */
    0x4a81, /* SUB */
    0x1d53, /* HKT */
    0x29ae, /* KNO */
    0xc03, /* DAD */
    0x9b7, /* CNX */
    0x25c6, /* JOG */
    0x1d6f, /* HLP */
    0x667, /* BTH */
    0x3d6c, /* PLM */
    0x3aa1, /* OVB */
    0xaf1, /* CXR */
    0x3d54, /* PKU */
    0x1c78, /* HDY */
    0x4a26, /* SRG */
    0x2835, /* KBV */
    0x3c8a, /* PEK */
    0x1d46, /* HKG */
    0x3ea6, /* PVG */
    0x80d, /* CAN */
    0x490d, /* SIN */
    0x2a8b, /* KUL */
    0xa74, /* CTU */
    0x4b37, /* SZX */
    0x4de4, /* TPE */
    0x2986, /* KMG */
    0x31ab, /* MNL */
    0x48e0, /* SHA */
    0x5d18, /* XIY */
    0x946, /* CKG */
    0x1cc7, /* HGH */
    0x3546, /* NKG */
    0x5d8d, /* XMN */
    0x8ce, /* CGO */
    0xa57, /* CSX */
    0x4c0e, /* TAO */
    0x1da3, /* HND */
    0x204d, /* ICN */
    0x3633, /* NRT */
    0x934, /* CJU */
    0x2917, /* KIX */
    0x198f, /* GMP */
    0x168a, /* FUK */
    0xa72, /* CTS */
    0x3940, /* OKA */
    0x3e92, /* PUS */
    0x226c, /* ITM */
    0x34ce, /* NGO */
    0x29c9, /* KOJ */
    0x4c04, /* TAE */
    0x2989, /* KMJ */
    0x4869, /* SDJ */
    0x34d2, /* NGS */
    0x2988, /* KMI */
    0x3309, /* MYJ */
    0x929, /* CJJ */
    0xe36, /* DRW */
    0x24f, /* ASP */
    0x310, /* AYQ */
    0x6b, /* ADL */
    0x3d6e, /* PLO */
    0x30c1, /* MGB */
    0x396f, /* OLP */
    0x5a4, /* BNE */
    0x39cb, /* OOL */
    0x9b2, /* CNS */
    0x56ae, /* VVO */
    0x28f5, /* KHV */
    0x4e55, /* TSV */
    0x3158, /* MKY */
    0x3dcc, /* POM */
    0x3058, /* MCY */
    0x45ca, /* ROK */
    0x1e68, /* HTI */
    0x1973, /* GLT */
    0x4b03, /* SYD */
    0x308b, /* MEL */
    0x831, /* CBR */
    0x1c20, /* HBA */
    0x2e53, /* LST */
    0x366b, /* NTL */
    0x5aa, /* BNK */
    0x8b2, /* CFS */
    0x2c67, /* LDH */
    0x5292, /* UUS */
    0x356a, /* NLK */
    0x340d, /* NAN */
    0x3d42, /* PKC */
    0x14b, /* AKL */
    0x8e2, /* CHC */
    0x5966, /* WLG */
    0x660d, /* ZQN */
    0x364d, /* NSN */
    0xe83, /* DUD */
    0x35e4, /* NPE */
    0x3d91, /* PMR */
    0x35eb, /* NPL */
    0x4e26, /* TRG */
    0x1d79, /* HLZ */
    0x4e4, /* BHE */
    0x22a2, /* IVC */
    0x45d3, /* ROT */
    0x8f3, /* CHT */
    0x1f6, /* APW */
    0x4c34, /* TBU */
    0x5415, /* VAV */
    0x1de0, /* HPA */
    0x1280, /* EUA */
    0x3673, /* NTT */
    0xae8, /* CXI */
};

#define AIRPORT_CODE_POOL_BITS_COUNT 409

// Total airport names: 409
static const char airport_name_pool[] =
    "Pago Pago\0" "Niue\0" "Fitiuta\0" "Honolulu\0" 
    "Kona International At Keahole\0" "Lihue\0" "Hilo\0" "Molokai\0" 
    "Kapalua\0" "Lanai\0" "Adak\0" "Nuku Hiva\0" "Hiva Oa-Atuona\0" "Ua Pou\0" 
    "Ua Huka\0" "Totegegie\0" "Ted Stevens Anchorage\0" "Los Angeles\0" 
    "San Francisco\0" "McCarran\0" "Seattle Tacoma\0" "Vancouver\0" 
    "San Diego\0" "Portland\0" "Metropolitan Oakland\0" 
    "Norman Y. Mineta San Jose\0" "Sacramento\0" 
    "John Wayne Airport-Orange County\0" "General Abelardo L. Rodríguez\0" 
    "Ontario\0" "Long Beach /Daugherty Field/\0" "Bob Hope\0" "Palm Springs\0" 
    "Victoria\0" "Kelowna\0" "Fresno Yosemite\0" "Santa Barbara Municipal\0" 
    "Phoenix Sky Harbor\0" "Denver\0" "Salt Lake City\0" "Calgary\0" 
    "Edmonton\0" "Albuquerque International Sunport\0" "El Paso\0" 
    "Licenciado Benito Juarez\0" "Don Miguel Hidalgo Y Costilla\0" 
    "General Mariano Escobedo\0" "Juan Santamaria\0" "Chicago O'Hare\0" 
    "Dallas Fort Worth\0" "George Bush Intercontinental Houston\0" 
    "Minneapolis-St Paul International/Wold-Chamberlain\0" "Chicago Midway\0" 
    "Dallas Love Field\0" "Lambert St Louis\0" "Nashville\0" 
    "Austin Bergstrom\0" "William P Hobby\0" "Louis Armstrong New Orleans\0" 
    "Kansas City\0" "San Antonio\0" "Eppley Airfield\0" 
    "Winnipeg / James Armstrong Richardson\0" "General Mitchell\0" "Mataveri\0" 
    "El Dorado\0" "Cancún\0" "Jorge Chávez\0" "José Martí\0" 
    "Hartsfield Jackson Atlanta\0" "John F Kennedy\0" "Lester B. Pearson\0" 
    "Charlotte Douglas\0" "Orlando\0" "Miami\0" "Newark Liberty\0" 
    "General Edward Lawrence Logan\0" "Detroit Metropolitan Wayne County\0" 
    "Fort Lauderdale Hollywood\0" "Orlando Executive\0" "La Guardia\0" 
    "Philadelphia\0" "Baltimore/Washington International Thurgood Marshall\0" 
    "Ronald Reagan Washington National\0" "Washington Dulles\0" "Tampa\0" 
    "Maturín\0" "Marechal Rondon\0" "Eduardo Gomes\0" "Princess Juliana\0" 
    "Campo Grande\0" "Governador Jorge Teixeira de Oliveira\0" 
    "Atlas Brasil Cantanhede\0" "Halifax / Stanfield\0" 
    "Comodoro Arturo Merino Benítez\0" "St. John's\0" "Deer Lake\0" 
    "St. Anthony\0" "Gander\0" "Williams Harbour\0" "St. Lewis (Fox Harbour)\0" 
    "Port Hope Simpson\0" "Guarulhos - Governador André Franco Montoro\0" 
    "Congonhas\0" "Presidente Juscelino Kubistschek\0" 
    "Rio Galeão – Tom Jobim\0" "Jorge Newbery Airpark\0" "Ministro Pistarini\0" 
    "Tancredo Neves\0" "Viracopos\0" "Santos Dumont\0" "Salgado Filho\0" 
    "Guararapes - Gilberto Freyre\0" "Deputado Luiz Eduardo Magalhães\0" 
    "Afonso Pena\0" "Pinto Martins\0" "Hercílio Luz\0" 
    "Val de Cans/Júlio Cezar Ribeiro\0" "Santa Genoveva\0" 
    "Eurico de Aguiar Salles\0" "Ingeniero Ambrosio Taravella\0" 
    "Governador Aluízio Alves\0" "St Pierre\0" "Fernando de Noronha\0" 
    "Godthaab / Nuuk\0" "Amílcar Cabral\0" "João Paulo II\0" "Lajes Field\0" 
    "Keflavik\0" "London Heathrow\0" "London Gatwick\0" "Dublin\0" 
    "Manchester\0" "Lisbon Portela\0" "London Stansted\0" "London Luton\0" 
    "Edinburgh\0" "Gran Canaria\0" "Birmingham\0" "Tenerife South\0" 
    "Francisco de Sá Carneiro\0" "Glasgow\0" "Faro\0" "Bristol\0" "Lanzarote\0" 
    "Fuerteventura\0" "Belfast\0" "Newcastle\0" "Mohammed V\0" 
    "Charles de Gaulle\0" "Amsterdam Airport Schiphol\0" "Frankfurt am Main\0" 
    "Adolfo Suárez Madrid–Barajas\0" "Barcelona\0" "Munich\0" 
    "Leonardo da Vinci–Fiumicino\0" "Zürich\0" "Copenhagen Kastrup\0" 
    "Palma De Mallorca\0" "Oslo Gardermoen\0" "Stockholm-Arlanda\0" 
    "Brussels\0" "Düsseldorf\0" "Vienna\0" "Malpensa\0" "Berlin-Tegel\0" 
    "Málaga\0" "Hamburg\0" "Geneva Cointrin\0" "OR Tambo\0" "Cape Town\0" 
    "King Shaka\0" "Khartoum\0" "Khrabrovo\0" "Ben Gurion\0" 
    "Beirut Rafic Hariri\0" "Chişinău\0" "Eleftherios Venizelos\0" 
    "Helsinki Vantaa\0" "Henri Coandă\0" "Boryspil\0" 
    "Heraklion International Nikos Kazantzakis\0" "Sofia\0" 
    "Thessaloniki Macedonia\0" "Riga\0" "Diagoras\0" "Ercan\0" 
    "Yasser Arafat\0" "Cairo\0" "Hurghada\0" "Sharm El Sheikh\0" 
    "Borg El Arab\0" "Atatürk\0" "Sheremetyevo\0" "King Abdulaziz\0" 
    "Sabiha Gökçen\0" "Domodedovo\0" "Antalya\0" "King Khaled\0" "Vnukovo\0" 
    "Pulkovo\0" "Esenboğa\0" "Adnan Menderes\0" "Addis Ababa Bole\0" 
    "Jomo Kenyatta\0" "Prince Mohammad Bin Abdulaziz\0" "Sochi\0" "Adana\0" 
    "Simferopol\0" "Dalaman\0" "Minsk National\0" "Milas Bodrum\0" "Mehrabad\0" 
    "Mashhad\0" "Imam Khomeini\0" "Shiraz Shahid Dastghaib\0" "Ahwaz\0" 
    "Kish\0" "Esfahan Shahid Beheshti\0" "Tabriz\0" "Bandar Abbas\0" 
    "Persian Gulf\0" "Kerman\0" "Shahid Sadooghi\0" "Abadan\0" "Bushehr\0" 
    "Zahedan\0" "Urmia\0" "Sardar-e-Jangal\0" "Dubai\0" "Abu Dhabi\0" 
    "Sharjah\0" "Sir Seewoosagur Ramgoolam\0" "Tbilisi\0" "Kurumoch\0" 
    "Roland Garros\0" "Al Maktoum\0" "Astrakhan\0" "Batumi\0" 
    "Ras Al Khaimah\0" "Kopitnari\0" "Izhevsk\0" "Ulyanovsk East\0" "Kabul\0" 
    "Herat\0" "Kandahar\0" "Mazar I Sharif\0" "Maimana\0" "Fayzabad\0" 
    "Koltsovo\0" "Ufa\0" "Roshchino\0" "Surgut\0" "Chelyabinsk Balandino\0" 
    "Bolshoye Savino\0" "Novy Urengoy\0" "Orenburg Central\0" 
    "Nizhnevartovsk\0" "Salekhard\0" "Khanty Mansiysk\0" "Noyabrsk\0" "Nadym\0" 
    "Magnitogorsk\0" "Kogalym\0" "Indira Gandhi\0" "Chhatrapati Shivaji\0" 
    "Kempegowda\0" "Netaji Subhash Chandra Bordoloi\0" "Chennai\0" "Cochin\0" 
    "Pune\0" "Sardar Vallabhbhai Patel\0" "Dabolim\0" "Jaipur\0" 
    "Chaudhary Charan Singh\0" "Lokpriya Gopinath Bordoloi\0" "Trivandrum\0" 
    "Biju Patnaik\0" "Calicut\0" "Lok Nayak Jayaprakash\0" 
    "Devi Ahilyabai Holkar\0" "Vishakhapatnam\0" "Sheikh ul Alam\0" 
    "Coimbatore\0" "Tribhuvan\0" "Gautam Buddha\0" "Biratnagar\0" "Nepalgunj\0" 
    "Taplejung\0" "Tumling Tar\0" "Bharatpur\0" "Bhadrapur\0" "Omsk Central\0" 
    "Yangon\0" "Mandalay\0" "Soekarno-Hatta\0" "Suvarnabhumi\0" "Don Mueang\0" 
    "Tan Son Nhat\0" "Noi Bai\0" "Juanda\0" "Phuket\0" "Kualanamu\0" 
    "Da Nang\0" "Chiang Mai\0" "Adi Sutjipto\0" "Halim Perdanakusuma\0" 
    "Hang Nadim\0" "Sultan Mahmud Badaruddin II\0" "Tolmachevo\0" "Cam Ranh\0" 
    "Sultan Syarif Kasim Ii (Simpang Tiga)\0" "Hat Yai\0" "Achmad Yani\0" 
    "Krabi\0" "Beijing Capital\0" "Chek Lap Kok\0" "Shanghai Pudong\0" 
    "Guangzhou Baiyun\0" "Singapore Changi\0" "Kuala Lumpur\0" 
    "Chengdu Shuangliu\0" "Shenzhen Bao'an\0" "Taiwan Taoyuan\0" 
    "Kunming Changshui\0" "Ninoy Aquino\0" "Shanghai Hongqiao\0" 
    "Xi'an Xianyang\0" "Chongqing Jiangbei\0" "Hangzhou Xiaoshan\0" 
    "Nanjing Lukou\0" "Xiamen Gaoqi\0" "Zhengzhou Xinzheng\0" 
    "Changsha Huanghua\0" "Liuting\0" "Tokyo Haneda\0" "Incheon\0" "Narita\0" 
    "Jeju\0" "Kansai\0" "Gimpo\0" "Fukuoka\0" "New Chitose\0" "Naha\0" 
    "Gimhae\0" "Osaka\0" "Chubu Centrair\0" "Kagoshima\0" "Daegu\0" 
    "Kumamoto\0" "Sendai\0" "Nagasaki\0" "Miyazaki\0" "Matsuyama\0" 
    "Cheongju\0" "Darwin\0" "Alice Springs\0" "Ayers Rock Connellan\0" 
    "Adelaide\0" "Port Lincoln\0" "Mount Gambier\0" "Olympic Dam\0" 
    "Brisbane\0" "Gold Coast\0" "Cairns\0" "Vladivostok\0" "Khabarovsk-Novy\0" 
    "Townsville\0" "Mackay\0" "Port Moresby Jacksons\0" "Sunshine Coast\0" 
    "Rockhampton\0" "Hamilton Island\0" "Gladstone\0" 
    "Sydney Kingsford Smith\0" "Melbourne\0" "Canberra\0" "Hobart\0" 
    "Launceston\0" "Newcastle\0" "Ballina Byron Gateway\0" "Coffs Harbour\0" 
    "Lord Howe Island\0" "Yuzhno-Sakhalinsk\0" "Norfolk Island\0" "Nadi\0" 
    "Yelizovo\0" "Auckland\0" "Christchurch\0" "Wellington\0" "Queenstown\0" 
    "Nelson\0" "Dunedin\0" "Hawke's Bay\0" "Palmerston North\0" 
    "New Plymouth\0" "Tauranga\0" "Hamilton\0" "Woodbourne\0" "Invercargill\0" 
    "Rotorua Regional\0" "Chatham Islands-Tuuta\0" "Faleolo\0" "Fua'amotu\0" 
    "Vava'u\0" "Lifuka Island\0" "Kaufana\0" "Kuini Lavenia\0" "Cassidy\0"
;

typedef struct {
    int8_t  std_quarters;    // std offset in 0.25h units
    int8_t  dst_quarters;    // dst offset in 0.25h units
    int32_t dst_start_utc;   // DST start (seconds since epoch)
    int32_t dst_end_utc;     // DST end (seconds since epoch)
    uint16_t name_offset;    // Index into airport_name_pool
    uint8_t  name_count;     // Number of codes in this bucket
} TzInfo;

// Total timezone variants: 60
static const TzInfo airport_tz_list[] = {
    { -44, -44, 0, 0, 0, 3 }, // Pacific/Pago_Pago, Pacific/Midway, Pacific/Niue (-11.00h/-11.00h)
    { -40, -40, 0, 0, 3, 7 }, // Pacific/Rarotonga, Pacific/Honolulu, Pacific/Tahiti (-10.00h/-10.00h)
    { -40, -36, 1741521600, 1762081200, 10, 1 }, // America/Adak (-10.00h/-9.00h)
    { -38, -38, 0, 0, 11, 4 }, // Pacific/Marquesas (-9.50h/-9.50h)
    { -36, -36, 0, 0, 15, 1 }, // Pacific/Gambier (-9.00h/-9.00h)
    { -36, -32, 1741518000, 1762077600, 16, 1 }, // America/Anchorage (-9.00h/-8.00h)
    { -32, -28, 1741514400, 1762074000, 17, 20 }, // America/Vancouver, America/Tijuana, America/Los_Angeles (-8.00h/-7.00h)
    { -28, -28, 0, 0, 37, 1 }, // America/Dawson_Creek, America/Mazatlan, America/Hermosillo (-7.00h/-7.00h)
    { -28, -24, 1741510800, 1762070400, 38, 6 }, // America/Edmonton, America/Denver, America/Inuvik (-7.00h/-6.00h)
    { -24, -24, 0, 0, 44, 4 }, // America/Regina, America/Guatemala, America/Tegucigalpa (-6.00h/-6.00h)
    { -24, -20, 1741507200, 1762066800, 48, 16 }, // America/Winnipeg, America/Chicago (-6.00h/-5.00h)
    { -24, -20, 1757217600, 1743908400, 64, 1 }, // Pacific/Easter (-6.00h/-5.00h)
    { -20, -20, 0, 0, 65, 3 }, // America/Coral_Harbour, America/Jamaica, America/Cancun (-5.00h/-5.00h)
    { -20, -16, 1741496400, 1762059600, 68, 1 }, // America/Havana (-5.00h/-4.00h)
    { -20, -16, 1741503600, 1762063200, 69, 17 }, // America/Toronto, America/Grand_Turk, America/Port-au-Prince (-5.00h/-4.00h)
    { -16, -16, 0, 0, 86, 7 }, // America/Santo_Domingo, America/Campo_Grande, America/Boa_Vista (-4.00h/-4.00h)
    { -16, -12, 1741500000, 1762059600, 93, 1 }, // America/Thule, America/Halifax, Atlantic/Bermuda (-4.00h/-3.00h)
    { -16, -12, 1757217600, 1743908400, 94, 1 }, // America/Santiago (-4.00h/-3.00h)
    { -14, -10, 1741496400, 1762056000, 95, 7 }, // America/St_Johns (-3.50h/-2.50h)
    { -12, -12, 0, 0, 102, 20 }, // Atlantic/Stanley, America/Cordoba, America/Buenos_Aires (-3.00h/-3.00h)
    { -12, -8, 1741496400, 1762056000, 122, 1 }, // America/Miquelon (-3.00h/-2.00h)
    { -8, -8, 0, 0, 123, 1 }, // America/Noronha (-2.00h/-2.00h)
    { -8, -4, 1743296400, 1761440400, 124, 1 }, // America/Godthab, America/Scoresbysund (-2.00h/-1.00h)
    { -4, -4, 0, 0, 125, 1 }, // Atlantic/Cape_Verde (-1.00h/-1.00h)
    { -4, 0, 1743296400, 1761440400, 126, 2 }, // Atlantic/Azores (-1.00h/0.00h)
    { 0, 0, 0, 0, 128, 1 }, // Atlantic/Reykjavik, Africa/Ouagadougou, Africa/Accra (0.00h/0.00h)
    { 0, 4, 1743296400, 1761440400, 129, 19 }, // Europe/London, Europe/Guernsey, Europe/Jersey (0.00h/1.00h)
    { 4, 4, 0, 0, 148, 1 }, // Africa/Algiers, Africa/Porto-Novo, Africa/Lagos (1.00h/1.00h)
    { 4, 8, 1743296400, 1761440400, 149, 20 }, // Europe/Brussels, Europe/Berlin, Europe/Amsterdam (1.00h/2.00h)
    { 8, 8, 0, 0, 169, 5 }, // Africa/Johannesburg, Africa/Gaborone, Africa/Mbabane (2.00h/2.00h)
    { 8, 12, 1743120000, 1761433200, 174, 1 }, // Asia/Jerusalem (2.00h/3.00h)
    { 8, 12, 1743285600, 1761426000, 175, 1 }, // Asia/Beirut (2.00h/3.00h)
    { 8, 12, 1743292800, 1761436800, 176, 1 }, // Europe/Chisinau (2.00h/3.00h)
    { 8, 12, 1743296400, 1761440400, 177, 10 }, // Europe/Tallinn, Europe/Helsinki, Europe/Mariehamn (2.00h/3.00h)
    { 8, 12, 1744416000, 1761346800, 187, 1 }, // Asia/Gaza (2.00h/3.00h)
    { 8, 12, 1745532000, 1761858000, 188, 4 }, // Africa/Cairo (2.00h/3.00h)
    { 12, 12, 0, 0, 192, 20 }, // Indian/Comoro, Indian/Mayotte, Indian/Antananarivo (3.00h/3.00h)
    { 14, 14, 0, 0, 212, 17 }, // Asia/Tehran (3.50h/3.50h)
    { 16, 16, 0, 0, 229, 14 }, // Indian/Mauritius, Indian/Reunion, Indian/Mahe (4.00h/4.00h)
    { 18, 18, 0, 0, 243, 6 }, // Asia/Kabul (4.50h/4.50h)
    { 20, 20, 0, 0, 249, 15 }, // Asia/Karachi, Asia/Qyzylorda, Asia/Oral (5.00h/5.00h)
    { 22, 22, 0, 0, 264, 20 }, // Asia/Calcutta, Asia/Colombo, Asia/Kolkata (5.50h/5.50h)
    { 23, 23, 0, 0, 284, 8 }, // Asia/Katmandu (5.75h/5.75h)
    { 24, 24, 0, 0, 292, 1 }, // Asia/Bishkek, Asia/Omsk, Asia/Dhaka (6.00h/6.00h)
    { 26, 26, 0, 0, 293, 2 }, // Asia/Rangoon, Indian/Cocos (6.50h/6.50h)
    { 28, 28, 0, 0, 295, 20 }, // Asia/Krasnoyarsk, Asia/Phnom_Penh, Asia/Vientiane (7.00h/7.00h)
    { 32, 32, 0, 0, 315, 20 }, // Asia/Taipei, Asia/Manila, Asia/Irkutsk (8.00h/8.00h)
    { 36, 36, 0, 0, 335, 20 }, // Pacific/Palau, Asia/Tokyo, Asia/Seoul (9.00h/9.00h)
    { 38, 38, 0, 0, 355, 3 }, // Australia/Darwin (9.50h/9.50h)
    { 38, 42, 1759593600, 1743872400, 358, 4 }, // Australia/Adelaide (9.50h/10.50h)
    { 40, 40, 0, 0, 362, 12 }, // Pacific/Port_Moresby, Pacific/Saipan, Pacific/Guam (10.00h/10.00h)
    { 40, 44, 1759593600, 1743868800, 374, 8 }, // Australia/Hobart, Australia/Sydney, Australia/Melbourne (10.00h/11.00h)
    { 42, 44, 1759593600, 1743865200, 382, 1 }, // Australia/Lord_Howe (10.50h/11.00h)
    { 44, 44, 0, 0, 383, 1 }, // Pacific/Efate, Pacific/Noumea, Pacific/Ponape (11.00h/11.00h)
    { 44, 48, 1759590000, 1743865200, 384, 1 }, // Pacific/Norfolk (11.00h/12.00h)
    { 48, 48, 0, 0, 385, 2 }, // Pacific/Fiji, Pacific/Tarawa, Pacific/Wallis (12.00h/12.00h)
    { 48, 52, 1758981600, 1743861600, 387, 14 }, // Pacific/Auckland (12.00h/13.00h)
    { 51, 55, 1758981600, 1743861600, 401, 1 }, // Pacific/Chatham (12.75h/13.75h)
    { 52, 52, 0, 0, 402, 6 }, // Pacific/Tongatapu, Pacific/Apia, Pacific/Enderbury (13.00h/13.00h)
    { 56, 56, 0, 0, 408, 1 }, // Pacific/Kiritimati (14.00h/14.00h)
};

#define AIRPORT_TZ_LIST_COUNT (sizeof(airport_tz_list)/sizeof(airport_tz_list[0]))
#define AIRPORT_CODE_POOL_COUNT 409
#define AIRPORT_NAME_POOL_COUNT 409
