// Auto-generated by generateAirportTzList.ts
// Generated on: 2025-04-24T18:57:23.970Z
// Year-specific DST data for 2025

#include <stdint.h>

// Total airport codes: 245
static const char airport_code_pool[] =
    "PPG" "IUE" "FTI" "HNL" "KOA" "LIH" "ITO" "MKK"
    "JHM" "LNY" "ADK" "NHV" "AUQ" "UAP" "GMR" "ANC"
    "LAX" "SFO" "LAS" "SEA" "YVR" "SAN" "PDX" "OAK"
    "SJC" "SMF" "PHX" "DEN" "SLC" "YYC" "YEG" "ABQ"
    "ELP" "MEX" "ORD" "DFW" "IAH" "MSP" "MDW" "DAL"
    "STL" "BNA" "AUS" "IPC" "CUN" "HAV" "ATL" "JFK"
    "YYZ" "CLT" "MCO" "MIA" "EWR" "BOS" "DTW" "FLL"
    "MUN" "CGB" "MAO" "SXM" "CGR" "PVH" "BVB" "YHZ"
    "SCL" "YYT" "YDF" "YAY" "YWM" "GRU" "CGH" "BSB"
    "GIG" "AEP" "EZE" "CNF" "VCP" "SDU" "POA" "FSP"
    "FEN" "GOH" "SID" "PDL" "TER" "DKR" "LHR" "LGW"
    "DUB" "MAN" "LIS" "STN" "LTN" "EDI" "LPA" "BHX"
    "CMN" "CDG" "AMS" "FRA" "MAD" "BCN" "MUC" "FCO"
    "ZRH" "CPH" "PMI" "JNB" "CPT" "TLV" "BEY" "KIV"
    "ATH" "HEL" "OTP" "KBP" "HER" "SOF" "GZA" "CAI"
    "IST" "SVO" "JED" "SAW" "DME" "AYT" "RUH" "VKO"
    "LED" "ESB" "THR" "MHD" "IKA" "SYZ" "AWZ" "KIH"
    "IFN" "TBZ" "BND" "PGU" "DXB" "AUH" "SHJ" "MRU"
    "TBS" "KUF" "RUN" "DWC" "ASF" "BUS" "KBL" "HEA"
    "FBD" "SVX" "UFA" "TJM" "SGC" "CEK" "PEE" "NUX"
    "REN" "NJC" "SLY" "DEL" "BOM" "BLR" "CCU" "MAA"
    "COK" "PNQ" "AMD" "GOI" "JAI" "KTM" "BWA" "BIR"
    "TMI" "OMS" "RGN" "MDL" "CGK" "BKK" "DMK" "SGN"
    "HAN" "SUB" "HKT" "KNO" "DAD" "CNX" "PEK" "HKG"
    "PVG" "CAN" "SIN" "KUL" "CTU" "SZX" "TPE" "KMG"
    "HND" "ICN" "NRT" "CJU" "KIX" "GMP" "FUK" "CTS"
    "OKA" "PUS" "DRW" "ASP" "AYQ" "ADL" "PLO" "MGB"
    "OLP" "BNE" "OOL" "CNS" "VVO" "KHV" "TSV" "SYD"
    "MEL" "CBR" "HBA" "LDH" "UUS" "NLK" "NAN" "PKC"
    "AKL" "CHC" "WLG" "ZQN" "NSN" "DUD" "NPE" "PMR"
    "CHT" "APW" "TBU" "EUA" "CXI"
;

// Total airport names: 245
static const char* airport_name_pool[] = {
    "Pago Pago",
    "Niue",
    "Fitiuta",
    "Honolulu",
    "Kona International At Keahole",
    "Lihue",
    "Hilo",
    "Molokai",
    "Kapalua",
    "Lanai",
    "Adak",
    "Nuku Hiva",
    "Hiva Oa-Atuona",
    "Ua Pou",
    "Totegegie",
    "Ted Stevens Anchorage",
    "Los Angeles",
    "San Francisco",
    "McCarran",
    "Seattle Tacoma",
    "Vancouver",
    "San Diego",
    "Portland",
    "Metropolitan Oakland",
    "Norman Y. Mineta San Jose",
    "Sacramento",
    "Phoenix Sky Harbor",
    "Denver",
    "Salt Lake City",
    "Calgary",
    "Edmonton",
    "Albuquerque International Sunport",
    "El Paso",
    "Licenciado Benito Juarez",
    "Chicago O'Hare",
    "Dallas Fort Worth",
    "George Bush Intercontinental Houston",
    "Minneapolis-St Paul International/Wold-Chamberlain",
    "Chicago Midway",
    "Dallas Love Field",
    "Lambert St Louis",
    "Nashville",
    "Austin Bergstrom",
    "Mataveri",
    "Cancún",
    "José Martí",
    "Hartsfield Jackson Atlanta",
    "John F Kennedy",
    "Lester B. Pearson",
    "Charlotte Douglas",
    "Orlando",
    "Miami",
    "Newark Liberty",
    "General Edward Lawrence Logan",
    "Detroit Metropolitan Wayne County",
    "Fort Lauderdale Hollywood",
    "Maturín",
    "Marechal Rondon",
    "Eduardo Gomes",
    "Princess Juliana",
    "Campo Grande",
    "Governador Jorge Teixeira de Oliveira",
    "Atlas Brasil Cantanhede",
    "Halifax / Stanfield",
    "Comodoro Arturo Merino Benítez",
    "St. John's",
    "Deer Lake",
    "St. Anthony",
    "Williams Harbour",
    "Guarulhos - Governador André Franco Montoro",
    "Congonhas",
    "Presidente Juscelino Kubistschek",
    "Rio Galeão – Tom Jobim",
    "Jorge Newbery Airpark",
    "Ministro Pistarini",
    "Tancredo Neves",
    "Viracopos",
    "Santos Dumont",
    "Salgado Filho",
    "St Pierre",
    "Fernando de Noronha",
    "Godthaab / Nuuk",
    "Amílcar Cabral",
    "João Paulo II",
    "Lajes Field",
    "Léopold Sédar Senghor",
    "London Heathrow",
    "London Gatwick",
    "Dublin",
    "Manchester",
    "Lisbon Portela",
    "London Stansted",
    "London Luton",
    "Edinburgh",
    "Gran Canaria",
    "Birmingham",
    "Mohammed V",
    "Charles de Gaulle",
    "Amsterdam Airport Schiphol",
    "Frankfurt am Main",
    "Adolfo Suárez Madrid–Barajas",
    "Barcelona",
    "Munich",
    "Leonardo da Vinci–Fiumicino",
    "Zürich",
    "Copenhagen Kastrup",
    "Palma De Mallorca",
    "OR Tambo",
    "Cape Town",
    "Ben Gurion",
    "Beirut Rafic Hariri",
    "Chişinău",
    "Eleftherios Venizelos",
    "Helsinki Vantaa",
    "Henri Coandă",
    "Boryspil",
    "Heraklion International Nikos Kazantzakis",
    "Sofia",
    "Yasser Arafat",
    "Cairo",
    "Atatürk",
    "Sheremetyevo",
    "King Abdulaziz",
    "Sabiha Gökçen",
    "Domodedovo",
    "Antalya",
    "King Khaled",
    "Vnukovo",
    "Pulkovo",
    "Esenboğa",
    "Mehrabad",
    "Mashhad",
    "Imam Khomeini",
    "Shiraz Shahid Dastghaib",
    "Ahwaz",
    "Kish",
    "Esfahan Shahid Beheshti",
    "Tabriz",
    "Bandar Abbas",
    "Persian Gulf",
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
    "Sir Seewoosagur Ramgoolam",
    "Tbilisi",
    "Kurumoch",
    "Roland Garros",
    "Al Maktoum",
    "Astrakhan",
    "Batumi",
    "Kabul",
    "Herat",
    "Fayzabad",
    "Koltsovo",
    "Ufa",
    "Roshchino",
    "Surgut",
    "Chelyabinsk Balandino",
    "Bolshoye Savino",
    "Novy Urengoy",
    "Orenburg Central",
    "Nizhnevartovsk",
    "Salekhard",
    "Indira Gandhi",
    "Chhatrapati Shivaji",
    "Kempegowda",
    "Netaji Subhash Chandra Bose",
    "Chennai",
    "Cochin",
    "Pune",
    "Sardar Vallabhbhai Patel",
    "Dabolim",
    "Jaipur",
    "Tribhuvan",
    "Gautam Buddha",
    "Biratnagar",
    "Tumling Tar",
    "Omsk Central",
    "Yangon",
    "Mandalay",
    "Soekarno-Hatta",
    "Suvarnabhumi",
    "Don Mueang",
    "Tan Son Nhat",
    "Noi Bai",
    "Juanda",
    "Phuket",
    "Kualanamu",
    "Da Nang",
    "Chiang Mai",
    "Beijing Capital",
    "Chek Lap Kok",
    "Shanghai Pudong",
    "Guangzhou Baiyun",
    "Singapore Changi",
    "Kuala Lumpur",
    "Chengdu Shuangliu",
    "Shenzhen Bao'an",
    "Taiwan Taoyuan",
    "Kunming Changshui",
    "Tokyo Haneda",
    "Incheon",
    "Narita",
    "Jeju",
    "Kansai",
    "Gimpo",
    "Fukuoka",
    "New Chitose",
    "Naha",
    "Gimhae",
    "Darwin",
    "Alice Springs",
    "Ayers Rock Connellan",
    "Adelaide",
    "Port Lincoln",
    "Mount Gambier",
    "Olympic Dam",
    "Brisbane",
    "Gold Coast",
    "Cairns",
    "Vladivostok",
    "Khabarovsk-Novy",
    "Townsville",
    "Sydney Kingsford Smith",
    "Melbourne",
    "Canberra",
    "Hobart",
    "Lord Howe Island",
    "Yuzhno-Sakhalinsk",
    "Norfolk Island",
    "Nadi",
    "Yelizovo",
    "Auckland",
    "Christchurch",
    "Wellington",
    "Queenstown",
    "Nelson",
    "Dunedin",
    "Hawke's Bay",
    "Palmerston North",
    "Chatham Islands-Tuuta",
    "Faleolo",
    "Fua'amotu",
    "Kaufana",
    "Cassidy",
};

typedef struct {
    float std_offset_hours;
    float dst_offset_hours;
    int64_t dst_start_utc;
    int64_t dst_end_utc;
    int name_offset; // Index into airport_code_pool & airport_name_pool
    int name_count;  // Number of unique airports for this tz variant
} TzInfo;

// Total timezone variants: 60
static const TzInfo airport_tz_list[] = {
    { -11.00f, -11.00f, 0LL, 0LL, 0, 3 }, // Pacific/Pago_Pago, Pacific/Midway, Pacific/Niue...
    { -10.00f, -10.00f, 0LL, 0LL, 3, 7 }, // Pacific/Rarotonga, Pacific/Honolulu, Pacific/Tahiti...
    { -10.00f, -9.00f, 1741521600LL, 1762081200LL, 10, 1 }, // America/Adak...
    { -9.50f, -9.50f, 0LL, 0LL, 11, 3 }, // Pacific/Marquesas...
    { -9.00f, -9.00f, 0LL, 0LL, 14, 1 }, // Pacific/Gambier...
    { -9.00f, -8.00f, 1741518000LL, 1762077600LL, 15, 1 }, // America/Anchorage...
    { -8.00f, -7.00f, 1741514400LL, 1762074000LL, 16, 10 }, // America/Vancouver, America/Tijuana, America/Los_Angeles...
    { -7.00f, -7.00f, 0LL, 0LL, 26, 1 }, // America/Dawson_Creek, America/Mazatlan, America/Hermosillo...
    { -7.00f, -6.00f, 1741510800LL, 1762070400LL, 27, 6 }, // America/Edmonton, America/Denver, America/Inuvik...
    { -6.00f, -6.00f, 0LL, 0LL, 33, 1 }, // America/Regina, America/Guatemala, America/Tegucigalpa...
    { -6.00f, -5.00f, 1741507200LL, 1762066800LL, 34, 9 }, // America/Winnipeg, America/Chicago...
    { -6.00f, -5.00f, 1757217600LL, 1743908400LL, 43, 1 }, // Pacific/Easter...
    { -5.00f, -5.00f, 0LL, 0LL, 44, 1 }, // America/Coral_Harbour, America/Jamaica, America/Cancun...
    { -5.00f, -4.00f, 1741496400LL, 1762059600LL, 45, 1 }, // America/Havana...
    { -5.00f, -4.00f, 1741503600LL, 1762063200LL, 46, 10 }, // America/Toronto, America/Grand_Turk, America/Port-au-Prince...
    { -4.00f, -4.00f, 0LL, 0LL, 56, 7 }, // America/Santo_Domingo, America/Campo_Grande, America/Boa_Vista...
    { -4.00f, -3.00f, 1741500000LL, 1762059600LL, 63, 1 }, // America/Thule, America/Halifax, Atlantic/Bermuda...
    { -4.00f, -3.00f, 1757217600LL, 1743908400LL, 64, 1 }, // America/Santiago...
    { -3.50f, -2.50f, 1741496400LL, 1762056000LL, 65, 4 }, // America/St_Johns...
    { -3.00f, -3.00f, 0LL, 0LL, 69, 10 }, // Atlantic/Stanley, America/Cordoba, America/Buenos_Aires...
    { -3.00f, -2.00f, 1741496400LL, 1762056000LL, 79, 1 }, // America/Miquelon...
    { -2.00f, -2.00f, 0LL, 0LL, 80, 1 }, // America/Noronha...
    { -2.00f, -1.00f, 1743296400LL, 1761440400LL, 81, 1 }, // America/Godthab, America/Scoresbysund...
    { -1.00f, -1.00f, 0LL, 0LL, 82, 1 }, // Atlantic/Cape_Verde...
    { -1.00f, 0.00f, 1743296400LL, 1761440400LL, 83, 2 }, // Atlantic/Azores...
    { 0.00f, 0.00f, 0LL, 0LL, 85, 1 }, // Atlantic/Reykjavik, Africa/Ouagadougou, Africa/Accra...
    { 0.00f, 1.00f, 1743296400LL, 1761440400LL, 86, 10 }, // Europe/London, Europe/Guernsey, Europe/Jersey...
    { 1.00f, 1.00f, 0LL, 0LL, 96, 1 }, // Africa/Algiers, Africa/Porto-Novo, Africa/Lagos...
    { 1.00f, 2.00f, 1743296400LL, 1761440400LL, 97, 10 }, // Europe/Brussels, Europe/Berlin, Europe/Amsterdam...
    { 2.00f, 2.00f, 0LL, 0LL, 107, 2 }, // Africa/Johannesburg, Africa/Gaborone, Africa/Mbabane...
    { 2.00f, 3.00f, 1743120000LL, 1761433200LL, 109, 1 }, // Asia/Jerusalem...
    { 2.00f, 3.00f, 1743285600LL, 1761426000LL, 110, 1 }, // Asia/Beirut...
    { 2.00f, 3.00f, 1743292800LL, 1761436800LL, 111, 1 }, // Europe/Chisinau...
    { 2.00f, 3.00f, 1743296400LL, 1761440400LL, 112, 6 }, // Europe/Tallinn, Europe/Helsinki, Europe/Mariehamn...
    { 2.00f, 3.00f, 1744416000LL, 1761346800LL, 118, 1 }, // Asia/Gaza...
    { 2.00f, 3.00f, 1745532000LL, 1761858000LL, 119, 1 }, // Africa/Cairo...
    { 3.00f, 3.00f, 0LL, 0LL, 120, 10 }, // Indian/Comoro, Indian/Mayotte, Indian/Antananarivo...
    { 3.50f, 3.50f, 0LL, 0LL, 130, 10 }, // Asia/Tehran...
    { 4.00f, 4.00f, 0LL, 0LL, 140, 10 }, // Indian/Mauritius, Indian/Reunion, Indian/Mahe...
    { 4.50f, 4.50f, 0LL, 0LL, 150, 3 }, // Asia/Kabul...
    { 5.00f, 5.00f, 0LL, 0LL, 153, 10 }, // Asia/Karachi, Asia/Qyzylorda, Asia/Oral...
    { 5.50f, 5.50f, 0LL, 0LL, 163, 10 }, // Asia/Calcutta, Asia/Colombo, Asia/Kolkata...
    { 5.75f, 5.75f, 0LL, 0LL, 173, 4 }, // Asia/Katmandu...
    { 6.00f, 6.00f, 0LL, 0LL, 177, 1 }, // Asia/Bishkek, Asia/Omsk, Asia/Dhaka...
    { 6.50f, 6.50f, 0LL, 0LL, 178, 2 }, // Asia/Rangoon, Indian/Cocos...
    { 7.00f, 7.00f, 0LL, 0LL, 180, 10 }, // Asia/Krasnoyarsk, Asia/Phnom_Penh, Asia/Vientiane...
    { 8.00f, 8.00f, 0LL, 0LL, 190, 10 }, // Asia/Taipei, Asia/Manila, Asia/Irkutsk...
    { 9.00f, 9.00f, 0LL, 0LL, 200, 10 }, // Pacific/Palau, Asia/Tokyo, Asia/Seoul...
    { 9.50f, 9.50f, 0LL, 0LL, 210, 3 }, // Australia/Darwin...
    { 9.50f, 10.50f, 1759593600LL, 1743872400LL, 213, 4 }, // Australia/Adelaide...
    { 10.00f, 10.00f, 0LL, 0LL, 217, 6 }, // Pacific/Port_Moresby, Pacific/Saipan, Pacific/Guam...
    { 10.00f, 11.00f, 1759593600LL, 1743868800LL, 223, 4 }, // Australia/Hobart, Australia/Sydney, Australia/Melbourne...
    { 10.50f, 11.00f, 1759593600LL, 1743865200LL, 227, 1 }, // Australia/Lord_Howe...
    { 11.00f, 11.00f, 0LL, 0LL, 228, 1 }, // Pacific/Efate, Pacific/Noumea, Pacific/Ponape...
    { 11.00f, 12.00f, 1759590000LL, 1743865200LL, 229, 1 }, // Pacific/Norfolk...
    { 12.00f, 12.00f, 0LL, 0LL, 230, 2 }, // Pacific/Fiji, Pacific/Tarawa, Pacific/Wallis...
    { 12.00f, 13.00f, 1758981600LL, 1743861600LL, 232, 8 }, // Pacific/Auckland...
    { 12.75f, 13.75f, 1758981600LL, 1743861600LL, 240, 1 }, // Pacific/Chatham...
    { 13.00f, 13.00f, 0LL, 0LL, 241, 3 }, // Pacific/Tongatapu, Pacific/Apia, Pacific/Enderbury...
    { 14.00f, 14.00f, 0LL, 0LL, 244, 1 }, // Pacific/Kiritimati...
};

#define AIRPORT_TZ_LIST_COUNT (sizeof(airport_tz_list)/sizeof(airport_tz_list[0]))
#define AIRPORT_CODE_POOL_COUNT 245
#define AIRPORT_NAME_POOL_COUNT 245
