// Auto-generated by generateAirportTzList.ts
// Generated on: 2025-04-24T22:10:45.033Z
// Year-specific DST data for 2025

#include <stdint.h>

// Total airport codes: 245  (codes listed for debug)
// Codes: PPG, IUE, FTI, HNL, KOA, LIH, ITO, MKK, JHM, LNY, ADK, NHV, AUQ, UAP, GMR, ANC, LAX, SFO, LAS, SEA, YVR, SAN, PDX, OAK, SJC, SMF, PHX, DEN, SLC, YYC, YEG, ABQ, ELP, MEX, ORD, DFW, IAH, MSP, MDW, DAL, STL, BNA, AUS, IPC, CUN, HAV, ATL, JFK, YYZ, CLT, MCO, MIA, EWR, BOS, DTW, FLL, MUN, CGB, MAO, SXM, CGR, PVH, BVB, YHZ, SCL, YYT, YDF, YAY, YWM, GRU, CGH, BSB, GIG, AEP, EZE, CNF, VCP, SDU, POA, FSP, FEN, GOH, SID, PDL, TER, DKR, LHR, LGW, DUB, MAN, LIS, STN, LTN, EDI, LPA, BHX, CMN, CDG, AMS, FRA, MAD, BCN, MUC, FCO, ZRH, CPH, PMI, JNB, CPT, TLV, BEY, KIV, ATH, HEL, OTP, KBP, HER, SOF, GZA, CAI, IST, SVO, JED, SAW, DME, AYT, RUH, VKO, LED, ESB, THR, MHD, IKA, SYZ, AWZ, KIH, IFN, TBZ, BND, PGU, DXB, AUH, SHJ, MRU, TBS, KUF, RUN, DWC, ASF, BUS, KBL, HEA, FBD, SVX, UFA, TJM, SGC, CEK, PEE, NUX, REN, NJC, SLY, DEL, BOM, BLR, CCU, MAA, COK, PNQ, AMD, GOI, JAI, KTM, BWA, BIR, TMI, OMS, RGN, MDL, CGK, BKK, DMK, SGN, HAN, SUB, HKT, KNO, DAD, CNX, PEK, HKG, PVG, CAN, SIN, KUL, CTU, SZX, TPE, KMG, HND, ICN, NRT, CJU, KIX, GMP, FUK, CTS, OKA, PUS, DRW, ASP, AYQ, ADL, PLO, MGB, OLP, BNE, OOL, CNS, VVO, KHV, TSV, SYD, MEL, CBR, HBA, LDH, UUS, NLK, NAN, PKC, AKL, CHC, WLG, ZQN, NSN, DUD, NPE, PMR, CHT, APW, TBU, EUA, CXI
static const uint16_t airport_code_pool_bits[] = {
    0x3de6, /* PPG */
    0x2284, /* IUE */
    0x1668, /* FTI */
    0x1dab, /* HNL */
    0x29c0, /* KOA */
    0x2d07, /* LIH */
    0x226e, /* ITO */
    0x314a, /* MKK */
    0x24ec, /* JHM */
    0x2db8, /* LNY */
    0x6a, /* ADK */
    0x34f5, /* NHV */
    0x290, /* AUQ */
    0x500f, /* UAP */
    0x1991, /* GMR */
    0x1a2, /* ANC */
    0x2c17, /* LAX */
    0x48ae, /* SFO */
    0x2c12, /* LAS */
    0x4880, /* SEA */
    0x62b1, /* YVR */
    0x480d, /* SAN */
    0x3c77, /* PDX */
    0x380a, /* OAK */
    0x4922, /* SJC */
    0x4985, /* SMF */
    0x3cf7, /* PHX */
    0xc8d, /* DEN */
    0x4962, /* SLC */
    0x6302, /* YYC */
    0x6086, /* YEG */
    0x30, /* ABQ */
    0x116f, /* ELP */
    0x3097, /* MEX */
    0x3a23, /* ORD */
    0xcb6, /* DFW */
    0x2007, /* IAH */
    0x324f, /* MSP */
    0x3076, /* MDW */
    0xc0b, /* DAL */
    0x4a6b, /* STL */
    0x5a0, /* BNA */
    0x292, /* AUS */
    0x21e2, /* IPC */
    0xa8d, /* CUN */
    0x1c15, /* HAV */
    0x26b, /* ATL */
    0x24aa, /* JFK */
    0x6319, /* YYZ */
    0x973, /* CLT */
    0x304e, /* MCO */
    0x3100, /* MIA */
    0x12d1, /* EWR */
    0x5d2, /* BOS */
    0xe76, /* DTW */
    0x156b, /* FLL */
    0x328d, /* MUN */
    0x8c1, /* CGB */
    0x300e, /* MAO */
    0x4aec, /* SXM */
    0x8d1, /* CGR */
    0x3ea7, /* PVH */
    0x6a1, /* BVB */
    0x60f9, /* YHZ */
    0x484b, /* SCL */
    0x6313, /* YYT */
    0x6065, /* YDF */
    0x6018, /* YAY */
    0x62cc, /* YWM */
    0x1a34, /* GRU */
    0x8c7, /* CGH */
    0x641, /* BSB */
    0x1906, /* GIG */
    0x8f, /* AEP */
    0x1324, /* EZE */
    0x9a5, /* CNF */
    0x544f, /* VCP */
    0x4874, /* SDU */
    0x3dc0, /* POA */
    0x164f, /* FSP */
    0x148d, /* FEN */
    0x19c7, /* GOH */
    0x4903, /* SID */
    0x3c6b, /* PDL */
    0x4c91, /* TER */
    0xd51, /* DKR */
    0x2cf1, /* LHR */
    0x2cd6, /* LGW */
    0xe81, /* DUB */
    0x300d, /* MAN */
    0x2d12, /* LIS */
    0x4a6d, /* STN */
    0x2e6d, /* LTN */
    0x1068, /* EDI */
    0x2de0, /* LPA */
    0x4f7, /* BHX */
    0x98d, /* CMN */
    0x866, /* CDG */
    0x192, /* AMS */
    0x1620, /* FRA */
    0x3003, /* MAD */
    0x44d, /* BCN */
    0x3282, /* MUC */
    0x144e, /* FCO */
    0x6627, /* ZRH */
    0x9e7, /* CPH */
    0x3d88, /* PMI */
    0x25a1, /* JNB */
    0x9f3, /* CPT */
    0x4d75, /* TLV */
    0x498, /* BEY */
    0x2915, /* KIV */
    0x267, /* ATH */
    0x1c8b, /* HEL */
    0x3a6f, /* OTP */
    0x282f, /* KBP */
    0x1c91, /* HER */
    0x49c5, /* SOF */
    0x1b20, /* GZA */
    0x808, /* CAI */
    0x2253, /* IST */
    0x4aae, /* SVO */
    0x2483, /* JED */
    0x4816, /* SAW */
    0xd84, /* DME */
    0x313, /* AYT */
    0x4687, /* RUH */
    0x554e, /* VKO */
    0x2c83, /* LED */
    0x1241, /* ESB */
    0x4cf1, /* THR */
    0x30e3, /* MHD */
    0x2140, /* IKA */
    0x4b19, /* SYZ */
    0x2d9, /* AWZ */
    0x2907, /* KIH */
    0x20ad, /* IFN */
    0x4c39, /* TBZ */
    0x5a3, /* BND */
    0x3cd4, /* PGU */
    0xee1, /* DXB */
    0x287, /* AUH */
    0x48e9, /* SHJ */
    0x3234, /* MRU */
    0x4c32, /* TBS */
    0x2a85, /* KUF */
    0x468d, /* RUN */
    0xec2, /* DWC */
    0x245, /* ASF */
    0x692, /* BUS */
    0x282b, /* KBL */
    0x1c80, /* HEA */
    0x1423, /* FBD */
    0x4ab7, /* SVX */
    0x50a0, /* UFA */
    0x4d2c, /* TJM */
    0x48c2, /* SGC */
    0x88a, /* CEK */
    0x3c84, /* PEE */
    0x3697, /* NUX */
    0x448d, /* REN */
    0x3522, /* NJC */
    0x4978, /* SLY */
    0xc8b, /* DEL */
    0x5cc, /* BOM */
    0x571, /* BLR */
    0x854, /* CCU */
    0x3000, /* MAA */
    0x9ca, /* COK */
    0x3db0, /* PNQ */
    0x183, /* AMD */
    0x19c8, /* GOI */
    0x2408, /* JAI */
    0x2a6c, /* KTM */
    0x6c0, /* BWA */
    0x511, /* BIR */
    0x4d88, /* TMI */
    0x3992, /* OMS */
    0x44cd, /* RGN */
    0x306b, /* MDL */
    0x8ca, /* CGK */
    0x54a, /* BKK */
    0xd8a, /* DMK */
    0x48cd, /* SGN */
    0x1c0d, /* HAN */
    0x4a81, /* SUB */
    0x1d53, /* HKT */
    0x29ae, /* KNO */
    0xc03, /* DAD */
    0x9b7, /* CNX */
    0x3c8a, /* PEK */
    0x1d46, /* HKG */
    0x3ea6, /* PVG */
    0x80d, /* CAN */
    0x490d, /* SIN */
    0x2a8b, /* KUL */
    0xa74, /* CTU */
    0x4b37, /* SZX */
    0x4de4, /* TPE */
    0x2986, /* KMG */
    0x1da3, /* HND */
    0x204d, /* ICN */
    0x3633, /* NRT */
    0x934, /* CJU */
    0x2917, /* KIX */
    0x198f, /* GMP */
    0x168a, /* FUK */
    0xa72, /* CTS */
    0x3940, /* OKA */
    0x3e92, /* PUS */
    0xe36, /* DRW */
    0x24f, /* ASP */
    0x310, /* AYQ */
    0x6b, /* ADL */
    0x3d6e, /* PLO */
    0x30c1, /* MGB */
    0x396f, /* OLP */
    0x5a4, /* BNE */
    0x39cb, /* OOL */
    0x9b2, /* CNS */
    0x56ae, /* VVO */
    0x28f5, /* KHV */
    0x4e55, /* TSV */
    0x4b03, /* SYD */
    0x308b, /* MEL */
    0x831, /* CBR */
    0x1c20, /* HBA */
    0x2c67, /* LDH */
    0x5292, /* UUS */
    0x356a, /* NLK */
    0x340d, /* NAN */
    0x3d42, /* PKC */
    0x14b, /* AKL */
    0x8e2, /* CHC */
    0x5966, /* WLG */
    0x660d, /* ZQN */
    0x364d, /* NSN */
    0xe83, /* DUD */
    0x35e4, /* NPE */
    0x3d91, /* PMR */
    0x8f3, /* CHT */
    0x1f6, /* APW */
    0x4c34, /* TBU */
    0x1280, /* EUA */
    0xae8, /* CXI */
};

#define AIRPORT_CODE_POOL_BITS_COUNT 245

// Total airport names: 245
static const char airport_name_pool[] =
    "Pago Pago\0" "Niue\0" "Fitiuta\0" "Honolulu\0" 
    "Kona International At Keahole\0" "Lihue\0" "Hilo\0" "Molokai\0" 
    "Kapalua\0" "Lanai\0" "Adak\0" "Nuku Hiva\0" "Hiva Oa-Atuona\0" "Ua Pou\0" 
    "Totegegie\0" "Ted Stevens Anchorage\0" "Los Angeles\0" "San Francisco\0" 
    "McCarran\0" "Seattle Tacoma\0" "Vancouver\0" "San Diego\0" "Portland\0" 
    "Metropolitan Oakland\0" "Norman Y. Mineta San Jose\0" "Sacramento\0" 
    "Phoenix Sky Harbor\0" "Denver\0" "Salt Lake City\0" "Calgary\0" 
    "Edmonton\0" "Albuquerque International Sunport\0" "El Paso\0" 
    "Licenciado Benito Juarez\0" "Chicago O'Hare\0" "Dallas Fort Worth\0" 
    "George Bush Intercontinental Houston\0" 
    "Minneapolis-St Paul International/Wold-Chamberlain\0" "Chicago Midway\0" 
    "Dallas Love Field\0" "Lambert St Louis\0" "Nashville\0" 
    "Austin Bergstrom\0" "Mataveri\0" "Cancún\0" "José Martí\0" 
    "Hartsfield Jackson Atlanta\0" "John F Kennedy\0" "Lester B. Pearson\0" 
    "Charlotte Douglas\0" "Orlando\0" "Miami\0" "Newark Liberty\0" 
    "General Edward Lawrence Logan\0" "Detroit Metropolitan Wayne County\0" 
    "Fort Lauderdale Hollywood\0" "Maturín\0" "Marechal Rondon\0" 
    "Eduardo Gomes\0" "Princess Juliana\0" "Campo Grande\0" 
    "Governador Jorge Teixeira de Oliveira\0" "Atlas Brasil Cantanhede\0" 
    "Halifax / Stanfield\0" "Comodoro Arturo Merino Benítez\0" "St. John's\0" 
    "Deer Lake\0" "St. Anthony\0" "Williams Harbour\0" 
    "Guarulhos - Governador André Franco Montoro\0" "Congonhas\0" 
    "Presidente Juscelino Kubistschek\0" "Rio Galeão – Tom Jobim\0" 
    "Jorge Newbery Airpark\0" "Ministro Pistarini\0" "Tancredo Neves\0" 
    "Viracopos\0" "Santos Dumont\0" "Salgado Filho\0" "St Pierre\0" 
    "Fernando de Noronha\0" "Godthaab / Nuuk\0" "Amílcar Cabral\0" 
    "João Paulo II\0" "Lajes Field\0" "Léopold Sédar Senghor\0" 
    "London Heathrow\0" "London Gatwick\0" "Dublin\0" "Manchester\0" 
    "Lisbon Portela\0" "London Stansted\0" "London Luton\0" "Edinburgh\0" 
    "Gran Canaria\0" "Birmingham\0" "Mohammed V\0" "Charles de Gaulle\0" 
    "Amsterdam Airport Schiphol\0" "Frankfurt am Main\0" 
    "Adolfo Suárez Madrid–Barajas\0" "Barcelona\0" "Munich\0" 
    "Leonardo da Vinci–Fiumicino\0" "Zürich\0" "Copenhagen Kastrup\0" 
    "Palma De Mallorca\0" "OR Tambo\0" "Cape Town\0" "Ben Gurion\0" 
    "Beirut Rafic Hariri\0" "Chişinău\0" "Eleftherios Venizelos\0" 
    "Helsinki Vantaa\0" "Henri Coandă\0" "Boryspil\0" 
    "Heraklion International Nikos Kazantzakis\0" "Sofia\0" "Yasser Arafat\0" 
    "Cairo\0" "Atatürk\0" "Sheremetyevo\0" "King Abdulaziz\0" "Sabiha Gökçen\0" 
    "Domodedovo\0" "Antalya\0" "King Khaled\0" "Vnukovo\0" "Pulkovo\0" 
    "Esenboğa\0" "Mehrabad\0" "Mashhad\0" "Imam Khomeini\0" 
    "Shiraz Shahid Dastghaib\0" "Ahwaz\0" "Kish\0" "Esfahan Shahid Beheshti\0" 
    "Tabriz\0" "Bandar Abbas\0" "Persian Gulf\0" "Dubai\0" "Abu Dhabi\0" 
    "Sharjah\0" "Sir Seewoosagur Ramgoolam\0" "Tbilisi\0" "Kurumoch\0" 
    "Roland Garros\0" "Al Maktoum\0" "Astrakhan\0" "Batumi\0" "Kabul\0" 
    "Herat\0" "Fayzabad\0" "Koltsovo\0" "Ufa\0" "Roshchino\0" "Surgut\0" 
    "Chelyabinsk Balandino\0" "Bolshoye Savino\0" "Novy Urengoy\0" 
    "Orenburg Central\0" "Nizhnevartovsk\0" "Salekhard\0" "Indira Gandhi\0" 
    "Chhatrapati Shivaji\0" "Kempegowda\0" "Netaji Subhash Chandra Bose\0" 
    "Chennai\0" "Cochin\0" "Pune\0" "Sardar Vallabhbhai Patel\0" "Dabolim\0" 
    "Jaipur\0" "Tribhuvan\0" "Gautam Buddha\0" "Biratnagar\0" "Tumling Tar\0" 
    "Omsk Central\0" "Yangon\0" "Mandalay\0" "Soekarno-Hatta\0" 
    "Suvarnabhumi\0" "Don Mueang\0" "Tan Son Nhat\0" "Noi Bai\0" "Juanda\0" 
    "Phuket\0" "Kualanamu\0" "Da Nang\0" "Chiang Mai\0" "Beijing Capital\0" 
    "Chek Lap Kok\0" "Shanghai Pudong\0" "Guangzhou Baiyun\0" 
    "Singapore Changi\0" "Kuala Lumpur\0" "Chengdu Shuangliu\0" 
    "Shenzhen Bao'an\0" "Taiwan Taoyuan\0" "Kunming Changshui\0" 
    "Tokyo Haneda\0" "Incheon\0" "Narita\0" "Jeju\0" "Kansai\0" "Gimpo\0" 
    "Fukuoka\0" "New Chitose\0" "Naha\0" "Gimhae\0" "Darwin\0" 
    "Alice Springs\0" "Ayers Rock Connellan\0" "Adelaide\0" "Port Lincoln\0" 
    "Mount Gambier\0" "Olympic Dam\0" "Brisbane\0" "Gold Coast\0" "Cairns\0" 
    "Vladivostok\0" "Khabarovsk-Novy\0" "Townsville\0" 
    "Sydney Kingsford Smith\0" "Melbourne\0" "Canberra\0" "Hobart\0" 
    "Lord Howe Island\0" "Yuzhno-Sakhalinsk\0" "Norfolk Island\0" "Nadi\0" 
    "Yelizovo\0" "Auckland\0" "Christchurch\0" "Wellington\0" "Queenstown\0" 
    "Nelson\0" "Dunedin\0" "Hawke's Bay\0" "Palmerston North\0" 
    "Chatham Islands-Tuuta\0" "Faleolo\0" "Fua'amotu\0" "Kaufana\0" "Cassidy\0"
;

typedef struct {
    int8_t  std_quarters;    // std offset in 0.25h units
    int8_t  dst_quarters;    // dst offset in 0.25h units
    int32_t dst_start_utc;   // DST start (seconds since epoch)
    int32_t dst_end_utc;     // DST end (seconds since epoch)
    uint16_t name_offset;    // Index into airport_name_pool
    uint8_t  name_count;     // Number of codes in this bucket
} TzInfo;

// Total timezone variants: 60
static const TzInfo airport_tz_list[] = {
    { -44, -44, 0, 0, 0, 3 }, // Pacific/Pago_Pago, Pacific/Midway, Pacific/Niue (-11.00h/-11.00h)
    { -40, -40, 0, 0, 3, 7 }, // Pacific/Rarotonga, Pacific/Honolulu, Pacific/Tahiti (-10.00h/-10.00h)
    { -40, -36, 1741521600, 1762081200, 10, 1 }, // America/Adak (-10.00h/-9.00h)
    { -38, -38, 0, 0, 11, 3 }, // Pacific/Marquesas (-9.50h/-9.50h)
    { -36, -36, 0, 0, 14, 1 }, // Pacific/Gambier (-9.00h/-9.00h)
    { -36, -32, 1741518000, 1762077600, 15, 1 }, // America/Anchorage (-9.00h/-8.00h)
    { -32, -28, 1741514400, 1762074000, 16, 10 }, // America/Vancouver, America/Tijuana, America/Los_Angeles (-8.00h/-7.00h)
    { -28, -28, 0, 0, 26, 1 }, // America/Dawson_Creek, America/Mazatlan, America/Hermosillo (-7.00h/-7.00h)
    { -28, -24, 1741510800, 1762070400, 27, 6 }, // America/Edmonton, America/Denver, America/Inuvik (-7.00h/-6.00h)
    { -24, -24, 0, 0, 33, 1 }, // America/Regina, America/Guatemala, America/Tegucigalpa (-6.00h/-6.00h)
    { -24, -20, 1741507200, 1762066800, 34, 9 }, // America/Winnipeg, America/Chicago (-6.00h/-5.00h)
    { -24, -20, 1757217600, 1743908400, 43, 1 }, // Pacific/Easter (-6.00h/-5.00h)
    { -20, -20, 0, 0, 44, 1 }, // America/Coral_Harbour, America/Jamaica, America/Cancun (-5.00h/-5.00h)
    { -20, -16, 1741496400, 1762059600, 45, 1 }, // America/Havana (-5.00h/-4.00h)
    { -20, -16, 1741503600, 1762063200, 46, 10 }, // America/Toronto, America/Grand_Turk, America/Port-au-Prince (-5.00h/-4.00h)
    { -16, -16, 0, 0, 56, 7 }, // America/Santo_Domingo, America/Campo_Grande, America/Boa_Vista (-4.00h/-4.00h)
    { -16, -12, 1741500000, 1762059600, 63, 1 }, // America/Thule, America/Halifax, Atlantic/Bermuda (-4.00h/-3.00h)
    { -16, -12, 1757217600, 1743908400, 64, 1 }, // America/Santiago (-4.00h/-3.00h)
    { -14, -10, 1741496400, 1762056000, 65, 4 }, // America/St_Johns (-3.50h/-2.50h)
    { -12, -12, 0, 0, 69, 10 }, // Atlantic/Stanley, America/Cordoba, America/Buenos_Aires (-3.00h/-3.00h)
    { -12, -8, 1741496400, 1762056000, 79, 1 }, // America/Miquelon (-3.00h/-2.00h)
    { -8, -8, 0, 0, 80, 1 }, // America/Noronha (-2.00h/-2.00h)
    { -8, -4, 1743296400, 1761440400, 81, 1 }, // America/Godthab, America/Scoresbysund (-2.00h/-1.00h)
    { -4, -4, 0, 0, 82, 1 }, // Atlantic/Cape_Verde (-1.00h/-1.00h)
    { -4, 0, 1743296400, 1761440400, 83, 2 }, // Atlantic/Azores (-1.00h/0.00h)
    { 0, 0, 0, 0, 85, 1 }, // Atlantic/Reykjavik, Africa/Ouagadougou, Africa/Accra (0.00h/0.00h)
    { 0, 4, 1743296400, 1761440400, 86, 10 }, // Europe/London, Europe/Guernsey, Europe/Jersey (0.00h/1.00h)
    { 4, 4, 0, 0, 96, 1 }, // Africa/Algiers, Africa/Porto-Novo, Africa/Lagos (1.00h/1.00h)
    { 4, 8, 1743296400, 1761440400, 97, 10 }, // Europe/Brussels, Europe/Berlin, Europe/Amsterdam (1.00h/2.00h)
    { 8, 8, 0, 0, 107, 2 }, // Africa/Johannesburg, Africa/Gaborone, Africa/Mbabane (2.00h/2.00h)
    { 8, 12, 1743120000, 1761433200, 109, 1 }, // Asia/Jerusalem (2.00h/3.00h)
    { 8, 12, 1743285600, 1761426000, 110, 1 }, // Asia/Beirut (2.00h/3.00h)
    { 8, 12, 1743292800, 1761436800, 111, 1 }, // Europe/Chisinau (2.00h/3.00h)
    { 8, 12, 1743296400, 1761440400, 112, 6 }, // Europe/Tallinn, Europe/Helsinki, Europe/Mariehamn (2.00h/3.00h)
    { 8, 12, 1744416000, 1761346800, 118, 1 }, // Asia/Gaza (2.00h/3.00h)
    { 8, 12, 1745532000, 1761858000, 119, 1 }, // Africa/Cairo (2.00h/3.00h)
    { 12, 12, 0, 0, 120, 10 }, // Indian/Comoro, Indian/Mayotte, Indian/Antananarivo (3.00h/3.00h)
    { 14, 14, 0, 0, 130, 10 }, // Asia/Tehran (3.50h/3.50h)
    { 16, 16, 0, 0, 140, 10 }, // Indian/Mauritius, Indian/Reunion, Indian/Mahe (4.00h/4.00h)
    { 18, 18, 0, 0, 150, 3 }, // Asia/Kabul (4.50h/4.50h)
    { 20, 20, 0, 0, 153, 10 }, // Asia/Karachi, Asia/Qyzylorda, Asia/Oral (5.00h/5.00h)
    { 22, 22, 0, 0, 163, 10 }, // Asia/Calcutta, Asia/Colombo, Asia/Kolkata (5.50h/5.50h)
    { 23, 23, 0, 0, 173, 4 }, // Asia/Katmandu (5.75h/5.75h)
    { 24, 24, 0, 0, 177, 1 }, // Asia/Bishkek, Asia/Omsk, Asia/Dhaka (6.00h/6.00h)
    { 26, 26, 0, 0, 178, 2 }, // Asia/Rangoon, Indian/Cocos (6.50h/6.50h)
    { 28, 28, 0, 0, 180, 10 }, // Asia/Krasnoyarsk, Asia/Phnom_Penh, Asia/Vientiane (7.00h/7.00h)
    { 32, 32, 0, 0, 190, 10 }, // Asia/Taipei, Asia/Manila, Asia/Irkutsk (8.00h/8.00h)
    { 36, 36, 0, 0, 200, 10 }, // Pacific/Palau, Asia/Tokyo, Asia/Seoul (9.00h/9.00h)
    { 38, 38, 0, 0, 210, 3 }, // Australia/Darwin (9.50h/9.50h)
    { 38, 42, 1759593600, 1743872400, 213, 4 }, // Australia/Adelaide (9.50h/10.50h)
    { 40, 40, 0, 0, 217, 6 }, // Pacific/Port_Moresby, Pacific/Saipan, Pacific/Guam (10.00h/10.00h)
    { 40, 44, 1759593600, 1743868800, 223, 4 }, // Australia/Hobart, Australia/Sydney, Australia/Melbourne (10.00h/11.00h)
    { 42, 44, 1759593600, 1743865200, 227, 1 }, // Australia/Lord_Howe (10.50h/11.00h)
    { 44, 44, 0, 0, 228, 1 }, // Pacific/Efate, Pacific/Noumea, Pacific/Ponape (11.00h/11.00h)
    { 44, 48, 1759590000, 1743865200, 229, 1 }, // Pacific/Norfolk (11.00h/12.00h)
    { 48, 48, 0, 0, 230, 2 }, // Pacific/Fiji, Pacific/Tarawa, Pacific/Wallis (12.00h/12.00h)
    { 48, 52, 1758981600, 1743861600, 232, 8 }, // Pacific/Auckland (12.00h/13.00h)
    { 51, 55, 1758981600, 1743861600, 240, 1 }, // Pacific/Chatham (12.75h/13.75h)
    { 52, 52, 0, 0, 241, 3 }, // Pacific/Tongatapu, Pacific/Apia, Pacific/Enderbury (13.00h/13.00h)
    { 56, 56, 0, 0, 244, 1 }, // Pacific/Kiritimati (14.00h/14.00h)
};

#define AIRPORT_TZ_LIST_COUNT (sizeof(airport_tz_list)/sizeof(airport_tz_list[0]))
#define AIRPORT_CODE_POOL_COUNT 245
#define AIRPORT_NAME_POOL_COUNT 245
