// Generated by Python script using zoneinfo
// Includes Standard & DST offsets and UTC transition timestamps for 2025.
// WARNING: DST rules accurate only for the generated year.

#include <stdint.h>

// Holds a single city name string
typedef struct {
    const char* name;
} TzCityName;

// Holds offset info and points to an array of names
typedef struct {
    float std_offset_hours; // Offset during standard time
    float dst_offset_hours; // Offset during daylight time (if applicable)
    int64_t dst_start_utc;  // UTC timestamp (time_t) for DST start (0 if N/A)
    int64_t dst_end_utc;    // UTC timestamp (time_t) for DST end (0 if N/A)
    const TzCityName* names; // Pointer to the array of names
    int name_count;         // How many names are in the array
} TzInfo;

static const TzCityName tz_names_0[] = {
    { "Midway" },
    { "Niue" },
    { "Pago Pago" },
    { "Samoa" },
};

static const TzCityName tz_names_1[] = {
    { "Adak" },
    { "Aleutian" },
    { "Atka" },
    { "Hawaii" },
    { "Honolulu" },
    { "Johnston" },
    { "Rarotonga" },
    { "Tahiti" },
};

static const TzCityName tz_names_2[] = {
    { "Marquesas" },
};

static const TzCityName tz_names_3[] = {
    { "Alaska" },
    { "Anchorage" },
    { "Gambier" },
    { "Juneau" },
    { "Metlakatla" },
    { "Nome" },
    { "Sitka" },
    { "Yakutat" },
};

static const TzCityName tz_names_4[] = {
    { "BajaNorte" },
    { "Ensenada" },
    { "Los Angeles" },
    { "Pacific" },
    { "Pitcairn" },
    { "Santa Isabel" },
    { "Tijuana" },
    { "Vancouver" },
};

static const TzCityName tz_names_5[] = {
    { "Arizona" },
    { "BajaSur" },
    { "Boise" },
    { "Cambridge Bay" },
    { "Ciudad Juarez" },
    { "Creston" },
    { "Dawson" },
    { "Dawson Creek" },
    { "Denver" },
    { "Edmonton" },
    { "Fort Nelson" },
    { "Hermosillo" },
    { "Inuvik" },
    { "Mazatlan" },
    { "Mountain" },
    { "Phoenix" },
    { "Shiprock" },
    { "Whitehorse" },
    { "Yellowknife" },
    { "Yukon" },
};

static const TzCityName tz_names_6[] = {
    { "Bahia Banderas" },
    { "Belize" },
    { "Beulah" },
    { "Center" },
    { "Central" },
    { "Chicago" },
    { "Chihuahua" },
    { "Costa Rica" },
    { "Easter" },
    { "EasterIsland" },
    { "El Salvador" },
    { "Galapagos" },
    { "General" },
    { "Guatemala" },
    { "Indiana-Starke" },
    { "Knox" },
    { "Knox IN" },
    { "Managua" },
    { "Matamoros" },
    { "Menominee" },
    { "Merida" },
    { "Mexico City" },
    { "Monterrey" },
    { "New Salem" },
    { "Ojinaga" },
    { "Rainy River" },
    { "Rankin Inlet" },
    { "Regina" },
    { "Resolute" },
    { "Saskatchewan" },
    { "Swift Current" },
    { "Tegucigalpa" },
    { "Tell City" },
    { "Winnipeg" },
};

static const TzCityName tz_names_7[] = {
    { "Acre" },
    { "Atikokan" },
    { "Bogota" },
    { "Cancun" },
    { "Cayman" },
    { "Coral Harbour" },
    { "Detroit" },
    { "East-Indiana" },
    { "Eastern" },
    { "Eirunepe" },
    { "Fort Wayne" },
    { "Grand Turk" },
    { "Guayaquil" },
    { "Havana" },
    { "Indianapolis" },
    { "Iqaluit" },
    { "Jamaica" },
    { "Lima" },
    { "Louisville" },
    { "Marengo" },
    { "Michigan" },
    { "Monticello" },
    { "Montreal" },
    { "Nassau" },
    { "New York" },
    { "Nipigon" },
    { "Panama" },
    { "Pangnirtung" },
    { "Petersburg" },
    { "Port-au-Prince" },
    { "Porto Acre" },
    { "Rio Branco" },
    { "Thunder Bay" },
    { "Toronto" },
    { "Vevay" },
    { "Vincennes" },
    { "Winamac" },
};

static const TzCityName tz_names_8[] = {
    { "Anguilla" },
    { "Antigua" },
    { "Aruba" },
    { "Atlantic" },
    { "Barbados" },
    { "Bermuda" },
    { "Blanc-Sablon" },
    { "Boa Vista" },
    { "Campo Grande" },
    { "Caracas" },
    { "Continental" },
    { "Cuiaba" },
    { "Curacao" },
    { "Dominica" },
    { "Glace Bay" },
    { "Goose Bay" },
    { "Grenada" },
    { "Guadeloupe" },
    { "Guyana" },
    { "Halifax" },
    { "Kralendijk" },
    { "La Paz" },
    { "Lower Princes" },
    { "Manaus" },
    { "Marigot" },
    { "Martinique" },
    { "Moncton" },
    { "Montserrat" },
    { "Port of Spain" },
    { "Porto Velho" },
    { "Puerto Rico" },
    { "Santiago" },
    { "Santo Domingo" },
    { "St Barthelemy" },
    { "St Kitts" },
    { "St Lucia" },
    { "St Thomas" },
    { "St Vincent" },
    { "Thule" },
    { "Tortola" },
    { "Virgin" },
    { "West" },
};

static const TzCityName tz_names_9[] = {
    { "Newfoundland" },
    { "St Johns" },
};

static const TzCityName tz_names_10[] = {
    { "Araguaina" },
    { "Asuncion" },
    { "Bahia" },
    { "Belem" },
    { "Buenos Aires" },
    { "Catamarca" },
    { "Cayenne" },
    { "ComodRivadavia" },
    { "Cordoba" },
    { "East" },
    { "Fortaleza" },
    { "Jujuy" },
    { "La Rioja" },
    { "Maceio" },
    { "Mendoza" },
    { "Miquelon" },
    { "Montevideo" },
    { "Palmer" },
    { "Paramaribo" },
    { "Punta Arenas" },
    { "Recife" },
    { "Rio Gallegos" },
    { "Rosario" },
    { "Rothera" },
    { "Salta" },
    { "San Juan" },
    { "San Luis" },
    { "Santarem" },
    { "Sao Paulo" },
    { "Stanley" },
    { "Tucuman" },
    { "Ushuaia" },
};

static const TzCityName tz_names_11[] = {
    { "DeNoronha" },
    { "Godthab" },
    { "Noronha" },
    { "Nuuk" },
    { "Scoresbysund" },
    { "South Georgia" },
};

static const TzCityName tz_names_12[] = {
    { "Azores" },
    { "Cape Verde" },
};

static const TzCityName tz_names_13[] = {
    { "Abidjan" },
    { "Accra" },
    { "Bamako" },
    { "Banjul" },
    { "Belfast" },
    { "Bissau" },
    { "Canary" },
    { "Casablanca" },
    { "Conakry" },
    { "Dakar" },
    { "Danmarkshavn" },
    { "Dublin" },
    { "El Aaiun" },
    { "Faeroe" },
    { "Faroe" },
    { "Freetown" },
    { "Guernsey" },
    { "Isle of Man" },
    { "Jersey" },
    { "Lisbon" },
    { "Lome" },
    { "London" },
    { "Madeira" },
    { "Monrovia" },
    { "Nouakchott" },
    { "Ouagadougou" },
    { "Reykjavik" },
    { "Sao Tome" },
    { "St Helena" },
    { "Timbuktu" },
    { "Troll" },
};

static const TzCityName tz_names_14[] = {
    { "Algiers" },
    { "Amsterdam" },
    { "Andorra" },
    { "Bangui" },
    { "Belgrade" },
    { "Berlin" },
    { "Bratislava" },
    { "Brazzaville" },
    { "Brussels" },
    { "Budapest" },
    { "Busingen" },
    { "Ceuta" },
    { "Copenhagen" },
    { "Douala" },
    { "Gibraltar" },
    { "Jan Mayen" },
    { "Kinshasa" },
    { "Lagos" },
    { "Libreville" },
    { "Ljubljana" },
    { "Longyearbyen" },
    { "Luanda" },
    { "Luxembourg" },
    { "Madrid" },
    { "Malabo" },
    { "Malta" },
    { "Monaco" },
    { "Ndjamena" },
    { "Niamey" },
    { "Oslo" },
    { "Paris" },
    { "Podgorica" },
    { "Porto-Novo" },
    { "Prague" },
    { "Rome" },
    { "San Marino" },
    { "Sarajevo" },
    { "Skopje" },
    { "Stockholm" },
    { "Tirane" },
    { "Tunis" },
    { "Vaduz" },
    { "Vatican" },
    { "Vienna" },
    { "Warsaw" },
    { "Zagreb" },
    { "Zurich" },
};

static const TzCityName tz_names_15[] = {
    { "Athens" },
    { "Beirut" },
    { "Blantyre" },
    { "Bucharest" },
    { "Bujumbura" },
    { "Cairo" },
    { "Chisinau" },
    { "Famagusta" },
    { "Gaborone" },
    { "Gaza" },
    { "Harare" },
    { "Hebron" },
    { "Helsinki" },
    { "Jerusalem" },
    { "Johannesburg" },
    { "Juba" },
    { "Kaliningrad" },
    { "Khartoum" },
    { "Kiev" },
    { "Kigali" },
    { "Kyiv" },
    { "Lubumbashi" },
    { "Lusaka" },
    { "Maputo" },
    { "Mariehamn" },
    { "Maseru" },
    { "Mbabane" },
    { "Nicosia" },
    { "Riga" },
    { "Sofia" },
    { "Tallinn" },
    { "Tel Aviv" },
    { "Tiraspol" },
    { "Tripoli" },
    { "Uzhgorod" },
    { "Vilnius" },
    { "Windhoek" },
    { "Zaporozhye" },
};

static const TzCityName tz_names_16[] = {
    { "Addis Ababa" },
    { "Aden" },
    { "Amman" },
    { "Antananarivo" },
    { "Asmara" },
    { "Asmera" },
    { "Baghdad" },
    { "Bahrain" },
    { "Comoro" },
    { "Damascus" },
    { "Dar es Salaam" },
    { "Djibouti" },
    { "Istanbul" },
    { "Kampala" },
    { "Kirov" },
    { "Kuwait" },
    { "Mayotte" },
    { "Minsk" },
    { "Mogadishu" },
    { "Moscow" },
    { "Nairobi" },
    { "Qatar" },
    { "Riyadh" },
    { "Simferopol" },
    { "Syowa" },
    { "Volgograd" },
};

static const TzCityName tz_names_17[] = {
    { "Tehran" },
};

static const TzCityName tz_names_18[] = {
    { "Astrakhan" },
    { "Baku" },
    { "Dubai" },
    { "Mahe" },
    { "Mauritius" },
    { "Muscat" },
    { "Reunion" },
    { "Samara" },
    { "Saratov" },
    { "Tbilisi" },
    { "Ulyanovsk" },
    { "Yerevan" },
};

static const TzCityName tz_names_19[] = {
    { "Kabul" },
};

static const TzCityName tz_names_20[] = {
    { "Almaty" },
    { "Aqtau" },
    { "Aqtobe" },
    { "Ashgabat" },
    { "Ashkhabad" },
    { "Atyrau" },
    { "Dushanbe" },
    { "Karachi" },
    { "Kerguelen" },
    { "Maldives" },
    { "Mawson" },
    { "Oral" },
    { "Qostanay" },
    { "Qyzylorda" },
    { "Samarkand" },
    { "Tashkent" },
    { "Vostok" },
    { "Yekaterinburg" },
};

static const TzCityName tz_names_21[] = {
    { "Calcutta" },
    { "Colombo" },
    { "Kolkata" },
};

static const TzCityName tz_names_22[] = {
    { "Kathmandu" },
    { "Katmandu" },
};

static const TzCityName tz_names_23[] = {
    { "Bishkek" },
    { "Chagos" },
    { "Dacca" },
    { "Dhaka" },
    { "Kashgar" },
    { "Omsk" },
    { "Thimbu" },
    { "Thimphu" },
    { "Urumqi" },
};

static const TzCityName tz_names_24[] = {
    { "Cocos" },
    { "Rangoon" },
    { "Yangon" },
};

static const TzCityName tz_names_25[] = {
    { "Bangkok" },
    { "Barnaul" },
    { "Christmas" },
    { "Davis" },
    { "Ho Chi Minh" },
    { "Hovd" },
    { "Jakarta" },
    { "Krasnoyarsk" },
    { "Novokuznetsk" },
    { "Novosibirsk" },
    { "Phnom Penh" },
    { "Pontianak" },
    { "Saigon" },
    { "Tomsk" },
    { "Vientiane" },
};

static const TzCityName tz_names_26[] = {
    { "Brunei" },
    { "Casey" },
    { "Choibalsan" },
    { "Chongqing" },
    { "Chungking" },
    { "Harbin" },
    { "Hong Kong" },
    { "Irkutsk" },
    { "Kuala Lumpur" },
    { "Kuching" },
    { "Macao" },
    { "Macau" },
    { "Makassar" },
    { "Manila" },
    { "Perth" },
    { "Shanghai" },
    { "Singapore" },
    { "Taipei" },
    { "Ujung Pandang" },
    { "Ulaanbaatar" },
    { "Ulan Bator" },
    { "West" },
};

static const TzCityName tz_names_27[] = {
    { "Eucla" },
};

static const TzCityName tz_names_28[] = {
    { "Chita" },
    { "Dili" },
    { "Jayapura" },
    { "Khandyga" },
    { "Palau" },
    { "Pyongyang" },
    { "Seoul" },
    { "Tokyo" },
    { "Yakutsk" },
};

static const TzCityName tz_names_29[] = {
    { "Adelaide" },
    { "Broken Hill" },
    { "Darwin" },
    { "North" },
    { "South" },
    { "Yancowinna" },
};

static const TzCityName tz_names_30[] = {
    { "ACT" },
    { "Brisbane" },
    { "Canberra" },
    { "Chuuk" },
    { "Currie" },
    { "DumontDUrville" },
    { "Guam" },
    { "Hobart" },
    { "Lindeman" },
    { "Macquarie" },
    { "Melbourne" },
    { "NSW" },
    { "Port Moresby" },
    { "Queensland" },
    { "Saipan" },
    { "Sydney" },
    { "Tasmania" },
    { "Truk" },
    { "Ust-Nera" },
    { "Victoria" },
    { "Vladivostok" },
    { "Yap" },
};

static const TzCityName tz_names_31[] = {
    { "LHI" },
    { "Lord Howe" },
};

static const TzCityName tz_names_32[] = {
    { "Bougainville" },
    { "Efate" },
    { "Guadalcanal" },
    { "Kosrae" },
    { "Magadan" },
    { "Norfolk" },
    { "Noumea" },
    { "Pohnpei" },
    { "Ponape" },
    { "Sakhalin" },
    { "Srednekolymsk" },
};

static const TzCityName tz_names_33[] = {
    { "Anadyr" },
    { "Auckland" },
    { "Fiji" },
    { "Funafuti" },
    { "Kamchatka" },
    { "Kwajalein" },
    { "Majuro" },
    { "McMurdo" },
    { "Nauru" },
    { "South Pole" },
    { "Tarawa" },
    { "Wake" },
    { "Wallis" },
};

static const TzCityName tz_names_34[] = {
    { "Chatham" },
};

static const TzCityName tz_names_35[] = {
    { "Apia" },
    { "Enderbury" },
    { "Fakaofo" },
    { "Kanton" },
    { "Tongatapu" },
};

static const TzCityName tz_names_36[] = {
    { "Kiritimati" },
};

// Main list mapping offsets/DST info to their respective name arrays
static const TzInfo tz_list[] = {
    { -11.00f, -11.00f, 0LL, 0LL, tz_names_0, 4 },
    { -10.00f, -10.00f, 0LL, 0LL, tz_names_1, 8 },
    { -9.50f, -9.50f, 0LL, 0LL, tz_names_2, 1 },
    { -9.00f, -8.00f, 1741489200LL, 1762048800LL, tz_names_3, 8 },
    { -8.00f, -7.00f, 1741489200LL, 1762048800LL, tz_names_4, 8 },
    { -7.00f, -6.00f, 1741489200LL, 1762048800LL, tz_names_5, 20 },
    { -6.00f, -6.00f, 0LL, 0LL, tz_names_6, 34 },
    { -5.00f, -4.00f, 1741489200LL, 1762048800LL, tz_names_7, 37 },
    { -4.00f, -3.00f, 1741489200LL, 1762048800LL, tz_names_8, 42 },
    { -3.50f, -2.50f, 1741489200LL, 1762048800LL, tz_names_9, 2 },
    { -3.00f, -3.00f, 0LL, 0LL, tz_names_10, 32 },
    { -2.00f, -1.00f, 1743292800LL, 1761436800LL, tz_names_11, 6 },
    { -1.00f, 0.00f, 1743296400LL, 1761440400LL, tz_names_12, 2 },
    { 0.00f, 1.00f, 1743300000LL, 1761444000LL, tz_names_13, 31 },
    { 1.00f, 2.00f, 1743303600LL, 1761447600LL, tz_names_14, 47 },
    { 2.00f, 3.00f, 1745542800LL, 1761868800LL, tz_names_15, 38 },
    { 3.00f, 3.00f, 0LL, 0LL, tz_names_16, 26 },
    { 3.50f, 3.50f, 0LL, 0LL, tz_names_17, 1 },
    { 4.00f, 4.00f, 0LL, 0LL, tz_names_18, 12 },
    { 4.50f, 4.50f, 0LL, 0LL, tz_names_19, 1 },
    { 5.00f, 5.00f, 0LL, 0LL, tz_names_20, 18 },
    { 5.50f, 5.50f, 0LL, 0LL, tz_names_21, 3 },
    { 5.75f, 5.75f, 0LL, 0LL, tz_names_22, 2 },
    { 6.00f, 6.00f, 0LL, 0LL, tz_names_23, 9 },
    { 6.50f, 6.50f, 0LL, 0LL, tz_names_24, 3 },
    { 7.00f, 7.00f, 0LL, 0LL, tz_names_25, 15 },
    { 8.00f, 8.00f, 0LL, 0LL, tz_names_26, 22 },
    { 8.75f, 8.75f, 0LL, 0LL, tz_names_27, 1 },
    { 9.00f, 9.00f, 0LL, 0LL, tz_names_28, 9 },
    { 9.50f, 10.50f, 1759633200LL, 1743908400LL, tz_names_29, 6 },
    { 10.00f, 10.00f, 0LL, 0LL, tz_names_30, 22 },
    { 10.50f, 11.00f, 1759633200LL, 1743904800LL, tz_names_31, 2 },
    { 11.00f, 11.00f, 0LL, 0LL, tz_names_32, 11 },
    { 12.00f, 12.00f, 0LL, 0LL, tz_names_33, 13 },
    { 12.75f, 13.75f, 1759032000LL, 1743912000LL, tz_names_34, 1 },
    { 13.00f, 13.00f, 0LL, 0LL, tz_names_35, 5 },
    { 14.00f, 14.00f, 0LL, 0LL, tz_names_36, 1 },
};

#define TZ_LIST_COUNT 37
